# SYSTEM OPTIMIZER - Maximum Performance Configuration
# Optimizes RAM, networking, profiles, and startup services

$ErrorActionPreference = "Continue"
Write-Host "=== SYSTEM OPTIMIZER ===" -ForegroundColor Cyan
Write-Host "Optimizing system for maximum performance..." -ForegroundColor Yellow

# 1. RAM Optimization
Write-Host "`n[1/8] Optimizing RAM..." -ForegroundColor Green
# Clear standby memory
if (Get-Command Clear-RecycleBin -ErrorAction SilentlyContinue) {
    Clear-RecycleBin -Force -ErrorAction SilentlyContinue
}

# Disable unnecessary services
$servicesToDisable = @(
    "DiagTrack",  # Diagnostic Tracking
    "dmwappushservice",  # WAP Push Message Routing
    "SysMain",  # Superfetch (can slow SSDs)
    "WSearch"  # Windows Search (if not needed)
)

foreach ($service in $servicesToDisable) {
    try {
        Stop-Service $service -Force -ErrorAction SilentlyContinue
        Set-Service $service -StartupType Disabled -ErrorAction SilentlyContinue
        Write-Host "  Disabled: $service" -ForegroundColor Gray
    } catch {}
}

# 2. Network Optimization
Write-Host "`n[2/8] Optimizing Network..." -ForegroundColor Green
# TCP/IP optimizations
netsh int tcp set global autotuninglevel=normal
netsh int tcp set global chimney=enabled
netsh int tcp set global dca=enabled
netsh int tcp set global netdma=enabled
netsh int tcp set global timestamps=disabled
netsh int tcp set heuristics disabled
netsh int tcp set supplemental Internet congestionprovider=ctcp

# DNS optimization (Cloudflare DNS)
$adapters = Get-NetAdapter | Where-Object {$_.Status -eq "Up"}
foreach ($adapter in $adapters) {
    Set-DnsClientServerAddress -InterfaceIndex $adapter.ifIndex -ServerAddresses ("1.1.1.1","1.0.0.1") -ErrorAction SilentlyContinue
}
Write-Host "  Set Cloudflare DNS (1.1.1.1)" -ForegroundColor Gray

# 3. Create Optimized PowerShell Profile
Write-Host "`n[3/8] Creating Optimized PowerShell Profile..." -ForegroundColor Green
$profileContent = @'
# OPTIMIZED POWERSHELL PROFILE
# Auto-generated by SYSTEM_OPTIMIZER

# Performance: Optimize console
$PSDefaultParameterValues['Out-File:Encoding'] = 'utf8'
$MaximumHistoryCount = 10000

# Aliases for common operations
Set-Alias -Name ll -Value Get-ChildItem
Set-Alias -Name grep -Value Select-String
Set-Alias -Name touch -Value New-Item
Set-Alias -Name which -Value Get-Command

# Quick navigation
function .. { Set-Location .. }
function ... { Set-Location ..\.. }
function .... { Set-Location ..\..\.. }

# System functions
function Get-PublicIP { (Invoke-WebRequest -Uri "https://api.ipify.org").Content }
function Clear-Memory { [System.GC]::Collect() }
function Get-DiskSpace { Get-PSDrive -PSProvider FileSystem | Select-Object Name, @{N="Used(GB)";E={[math]::Round($_.Used/1GB,2)}}, @{N="Free(GB)";E={[math]::Round($_.Free/1GB,2)}} }

# Cloudflare functions
function Deploy-SpiralSafe {
    Set-Location C:\Users\iamto\SpiralSafe-FromGitHub\cloudflare-workers-deployment
    python build.py
    wrangler deploy
}

function Start-CloudflareTunnel {
    Start-Process powershell -ArgumentList "-NoProfile -Command cloudflared tunnel run spiralsafe-tunnel" -WindowStyle Hidden
}

# Development shortcuts
function gs { git status }
function gp { git pull }
function gc { param($msg) git commit -m $msg }
function gps { git push }

# Logdy integration
function Start-Logdy {
    Start-Process powershell -ArgumentList "-NoProfile -Command logdy" -WindowStyle Normal
}

# System monitoring
function Get-SystemStatus {
    Write-Host "=== SYSTEM STATUS ===" -ForegroundColor Cyan
    Write-Host "RAM Usage: " -NoNewline
    $ram = Get-CimInstance Win32_OperatingSystem
    $usedRAM = [math]::Round(($ram.TotalVisibleMemorySize - $ram.FreePhysicalMemory) / 1MB, 2)
    $totalRAM = [math]::Round($ram.TotalVisibleMemorySize / 1MB, 2)
    Write-Host "$usedRAM GB / $totalRAM GB" -ForegroundColor Yellow

    Write-Host "CPU Usage: " -NoNewline
    $cpu = Get-CimInstance Win32_Processor | Measure-Object -Property LoadPercentage -Average
    Write-Host "$($cpu.Average)%" -ForegroundColor Yellow

    Write-Host "Disk Space: " -ForegroundColor Yellow
    Get-DiskSpace
}

# Startup message
Write-Host "Optimized PowerShell Profile Loaded" -ForegroundColor Green
Write-Host "Type 'Get-SystemStatus' for system info" -ForegroundColor Gray
'@

$profilePath = $PROFILE.CurrentUserAllHosts
$profileDir = Split-Path $profilePath -Parent
if (!(Test-Path $profileDir)) {
    New-Item -ItemType Directory -Path $profileDir -Force | Out-Null
}
$profileContent | Out-File $profilePath -Encoding UTF8 -Force
Write-Host "  Profile created: $profilePath" -ForegroundColor Gray

# 4. Create System Aliases
Write-Host "`n[4/8] Creating System Aliases..." -ForegroundColor Green
$aliasesContent = @'
# System Aliases
DOSKEY ls=dir /b $*
DOSKEY ll=dir $*
DOSKEY clear=cls
DOSKEY cat=type $*
DOSKEY grep=findstr $*
DOSKEY rm=del $*
DOSKEY cp=copy $*
DOSKEY mv=move $*
'@
$aliasesPath = "$env:USERPROFILE\system_aliases.cmd"
$aliasesContent | Out-File $aliasesPath -Encoding ASCII -Force
Write-Host "  Aliases created: $aliasesPath" -ForegroundColor Gray

# 5. Steam and Game Optimization
Write-Host "`n[5/8] Optimizing Steam and Game Settings..." -ForegroundColor Green
$steamLaunchOptions = "-high -nojoy -novid -freq 165 -refresh 165 +fps_max 165"
Write-Host "  Recommended Battlefield 6 Launch Options:" -ForegroundColor Gray
Write-Host "  $steamLaunchOptions" -ForegroundColor Yellow

# Create game optimization script
$gameOptScript = @'
# Game Performance Optimizer
Write-Host "Optimizing for gaming..." -ForegroundColor Cyan

# Set high performance power plan
powercfg /setactive 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c

# Disable Windows Game Bar
Set-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\GameDVR" -Name "AppCaptureEnabled" -Value 0 -Force
Set-ItemProperty -Path "HKCU:\System\GameConfigStore" -Name "GameDVR_Enabled" -Value 0 -Force

# GPU optimizations
Write-Host "Apply these in NVIDIA Control Panel:" -ForegroundColor Yellow
Write-Host "- Power Management: Prefer Maximum Performance" -ForegroundColor Gray
Write-Host "- Texture Filtering: High Performance" -ForegroundColor Gray
Write-Host "- Threaded Optimization: On" -ForegroundColor Gray

Write-Host "Done! Restart Steam for changes to take effect." -ForegroundColor Green
'@
$gameOptScript | Out-File "$env:USERPROFILE\Optimize-Gaming.ps1" -Encoding UTF8 -Force

# 6. Cloudflare Tunnel Startup Service
Write-Host "`n[6/8] Setting up Cloudflare Tunnel Auto-Start..." -ForegroundColor Green
$startupScript = @'
@echo off
start /min powershell -WindowStyle Hidden -Command "cloudflared tunnel run spiralsafe-tunnel"
'@
$startupPath = "$env:APPDATA\Microsoft\Windows\Start Menu\Programs\Startup\cloudflare-tunnel.bat"
$startupScript | Out-File $startupPath -Encoding ASCII -Force
Write-Host "  Startup script created: $startupPath" -ForegroundColor Gray

# 7. Logdy Configuration
Write-Host "`n[7/8] Configuring Logdy..." -ForegroundColor Green
$logdyConfig = @"
{
  "port": 8080,
  "host": "0.0.0.0",
  "ui": {
    "theme": "dark",
    "refresh": 1000
  }
}
"@
$logdyConfigPath = "$env:USERPROFILE\.logdy\config.json"
$logdyConfigDir = Split-Path $logdyConfigPath -Parent
if (!(Test-Path $logdyConfigDir)) {
    New-Item -ItemType Directory -Path $logdyConfigDir -Force | Out-Null
}
$logdyConfig | Out-File $logdyConfigPath -Encoding UTF8 -Force
Write-Host "  Logdy configured: $logdyConfigPath" -ForegroundColor Gray

# 8. Create Master Control Dashboard
Write-Host "`n[8/8] Creating Master Control Dashboard..." -ForegroundColor Green
$dashboardScript = @'
# MASTER CONTROL DASHBOARD
function Show-Dashboard {
    Clear-Host
    Write-Host "=====================================" -ForegroundColor Cyan
    Write-Host "   MASTER CONTROL DASHBOARD" -ForegroundColor Yellow
    Write-Host "=====================================" -ForegroundColor Cyan
    Write-Host ""

    # System Status
    Get-SystemStatus

    Write-Host "`n=== SERVICES ===" -ForegroundColor Cyan
    $cfTunnel = Get-Process cloudflared -ErrorAction SilentlyContinue
    Write-Host "Cloudflare Tunnel: " -NoNewline
    if ($cfTunnel) { Write-Host "RUNNING" -ForegroundColor Green } else { Write-Host "STOPPED" -ForegroundColor Red }

    Write-Host "`n=== QUICK ACTIONS ===" -ForegroundColor Cyan
    Write-Host "[1] Deploy SpiralSafe to Cloudflare"
    Write-Host "[2] Start Cloudflare Tunnel"
    Write-Host "[3] Start Logdy"
    Write-Host "[4] Optimize for Gaming"
    Write-Host "[5] Clean System Memory"
    Write-Host "[6] System Status"
    Write-Host "[Q] Quit"
    Write-Host ""

    $choice = Read-Host "Select action"
    switch ($choice) {
        "1" { Deploy-SpiralSafe }
        "2" { Start-CloudflareTunnel }
        "3" { Start-Logdy }
        "4" { & "$env:USERPROFILE\Optimize-Gaming.ps1" }
        "5" { Clear-Memory; Write-Host "Memory cleared" -ForegroundColor Green }
        "6" { Get-SystemStatus }
        "Q" { return }
    }

    if ($choice -ne "Q") {
        Read-Host "`nPress Enter to continue"
        Show-Dashboard
    }
}

# Auto-show dashboard
Show-Dashboard
'@
$dashboardScript | Out-File "$env:USERPROFILE\Dashboard.ps1" -Encoding UTF8 -Force
Write-Host "  Dashboard created: $env:USERPROFILE\Dashboard.ps1" -ForegroundColor Gray

# Summary
Write-Host "`n=== OPTIMIZATION COMPLETE ===" -ForegroundColor Green
Write-Host "Created files:" -ForegroundColor Yellow
Write-Host "  - PowerShell Profile: $profilePath"
Write-Host "  - System Aliases: $env:USERPROFILE\system_aliases.cmd"
Write-Host "  - Game Optimizer: $env:USERPROFILE\Optimize-Gaming.ps1"
Write-Host "  - Master Dashboard: $env:USERPROFILE\Dashboard.ps1"
Write-Host "  - Cloudflare Auto-start: $startupPath"
Write-Host "`nRun 'Dashboard' to access Master Control" -ForegroundColor Cyan
Write-Host "Restart PowerShell to load new profile" -ForegroundColor Cyan
